// Diccionario PT→ES para términos frecuentes de reseñas Olist (en portugués).
// Compartido entre la tarjeta de palabras y el insight del header de P5.
// Si un filtro saca una palabra no listada, se devuelve el original (fallback).
export type Idioma = "pt" | "es";

export const PT_ES: Record<string, string> = {
  // logística / entrega
  recebi: "recibí",
  receber: "recibir",
  recebido: "recibido",
  entrega: "entrega",
  entregue: "entregado",
  entregaram: "entregaron",
  entregou: "entregó",
  chegou: "llegó",
  chegaram: "llegaron",
  prazo: "plazo",
  prazos: "plazos",
  ainda: "todavía",
  aguardando: "esperando",
  aguardo: "espero",
  agora: "ahora",
  antes: "antes",
  dias: "días",
  data: "fecha",
  previsto: "previsto",
  dentro: "dentro",
  correios: "correos",
  demorou: "tardó",
  demora: "demora",
  atraso: "retraso",
  atrasado: "retrasado",
  // pedido / producto
  pedido: "pedido",
  pedi: "pedí",
  produto: "producto",
  produtos: "productos",
  unidades: "unidades",
  faltando: "faltan",
  falta: "falta",
  defeito: "defecto",
  errado: "equivocado",
  quebrado: "roto",
  mercadoria: "mercancía",
  conforme: "conforme",
  certo: "correcto",
  certinho: "todo correcto",
  estado: "estado",
  nota: "nota (factura)",
  fiscal: "fiscal",
  // tienda / atención
  loja: "tienda",
  site: "sitio web",
  contato: "contacto",
  resposta: "respuesta",
  retorno: "respuesta",
  atendimento: "atención",
  empresa: "empresa",
  vendedor: "vendedor",
  problema: "problema",
  // dinero
  paguei: "pagué",
  "preço": "precio",
  dinheiro: "dinero",
  "devolução": "devolución",
  reembolso: "reembolso",
  // valoración positiva
  recomendo: "recomiendo",
  excelente: "excelente",
  "ótimo": "excelente",
  otimo: "excelente",
  "ótima": "excelente",
  super: "súper",
  "rápida": "rápida",
  "rápido": "rápido",
  rapida: "rápida",
  rapido: "rápido",
  gostei: "me gustó",
  "parabéns": "felicidades",
  perfeito: "perfecto",
  adorei: "me encantó",
  amei: "me encantó",
  lindo: "precioso",
  embalado: "bien embalado",
  satisfeita: "satisfecha",
  satisfeito: "satisfecho",
  obrigado: "gracias",
  sempre: "siempre",
  // conectores / varios
  apenas: "solo",
  somente: "solamente",
  "porém": "pero",
  pois: "pues",
  outro: "otro",
  quero: "quiero",
  nada: "nada",
  momento: "momento",
  tive: "tuve",
  dois: "dos",
  duas: "dos",
  "está": "está",
  "não": "no",
  veio: "llegó",
  nunca: "nunca",
  ruim: "malo",
  "péssimo": "pésimo",
  pessima: "pésima",
  "horrível": "horrible",
};

/** Traduce un término PT→ES si el idioma es "es"; si no hay match, devuelve el original. */
export function traducir(t: string, idioma: Idioma): string {
  if (idioma !== "es") return t;
  return PT_ES[t] ?? PT_ES[t.toLowerCase()] ?? t;
}
