// Traducciones a español. Aplicadas solo en la capa de presentación
// (los datos en SQL Server siguen con el nombre original de Olist).

const CATEGORIAS_ES: Record<string, string> = {
  agro_industry_and_commerce: "Agroindustria y comercio",
  air_conditioning: "Aire acondicionado",
  art: "Arte",
  arts_and_craftmanship: "Manualidades",
  audio: "Audio",
  auto: "Automotriz",
  baby: "Bebés",
  bed_bath_table: "Cama, baño y mesa",
  books_general_interest: "Libros (interés general)",
  books_imported: "Libros importados",
  books_technical: "Libros técnicos",
  cds_dvds_musicals: "CDs, DVDs y musicales",
  christmas_supplies: "Artículos de Navidad",
  cine_photo: "Cine y fotografía",
  computers: "Computadoras",
  computers_accessories: "Computación y accesorios",
  consoles_games: "Consolas y videojuegos",
  construction_tools_construction: "Herramientas de construcción",
  construction_tools_lights: "Herramientas e iluminación",
  construction_tools_safety: "Herramientas de seguridad",
  cool_stuff: "Productos novedosos",
  costruction_tools_garden: "Herramientas de jardín",
  costruction_tools_tools: "Herramientas",
  diapers_and_hygiene: "Pañales e higiene",
  drinks: "Bebidas",
  dvds_blu_ray: "DVDs y Blu-ray",
  electronics: "Electrónica",
  fashio_female_clothing: "Moda femenina",
  fashion_bags_accessories: "Moda · bolsos y accesorios",
  fashion_childrens_clothes: "Ropa infantil",
  fashion_female_clothing: "Moda femenina",
  fashion_male_clothing: "Moda masculina",
  fashion_shoes: "Calzado",
  fashion_sport: "Moda deportiva",
  fashion_underwear_beach: "Lencería y baño",
  fixed_telephony: "Telefonía fija",
  flowers: "Flores",
  food: "Alimentos",
  food_drink: "Comida y bebida",
  furniture_bedroom: "Muebles de dormitorio",
  furniture_decor: "Muebles y decoración",
  furniture_living_room: "Muebles de sala",
  furniture_mattress_and_upholstery: "Colchones y tapicería",
  garden_tools: "Herramientas de jardín",
  health_beauty: "Salud y belleza",
  home_appliances: "Electrodomésticos",
  home_appliances_2: "Electrodomésticos (otros)",
  home_comfort_2: "Confort del hogar (otros)",
  home_confort: "Confort del hogar",
  home_construction: "Construcción y hogar",
  housewares: "Artículos del hogar",
  industry_commerce_and_business: "Industria y comercio",
  kitchen_dining_laundry_garden_furniture: "Cocina, comedor y lavandería",
  la_cuisine: "La cocina",
  luggage_accessories: "Equipaje y accesorios",
  market_place: "Marketplace",
  music: "Música",
  musical_instruments: "Instrumentos musicales",
  office_furniture: "Muebles de oficina",
  party_supplies: "Artículos de fiesta",
  pc_gamer: "PC Gamer",
  perfumery: "Perfumería",
  pet_shop: "Mascotas",
  portateis_cozinha_e_preparadores_de_alimentos: "Cocina · preparadores de alimentos",
  security_and_services: "Seguridad y servicios",
  signaling_and_security: "Señalización y seguridad",
  small_appliances: "Pequeños electrodomésticos",
  small_appliances_home_oven_and_coffee: "Hornos y cafeteras",
  sports_leisure: "Deportes y ocio",
  stationery: "Papelería",
  tablets_printing_image: "Tablets, impresión e imagen",
  telephony: "Telefonía",
  toys: "Juguetes",
  watches_gifts: "Relojes y regalos",
};

export function categoriaEs(en: string | undefined | null): string {
  if (!en) return "—";
  return CATEGORIAS_ES[en] ?? en.replace(/_/g, " ");
}

// Palabras más comunes de las reseñas Olist (originalmente en portugués)
const PALABRAS_ES: Record<string, string> = {
  // negativas / entrega
  recebi: "recibí",
  recebido: "recibido",
  entregue: "entregado",
  entregar: "entregar",
  entrega: "entrega",
  chegou: "llegó",
  chegar: "llegar",
  ainda: "todavía",
  apenas: "apenas",
  prazo: "plazo",
  pedido: "pedido",
  produtos: "productos",
  produto: "producto",
  comprei: "compré",
  comprar: "comprar",
  comprou: "compró",
  compra: "compra",
  esperando: "esperando",
  espero: "espero",
  veio: "vino",
  vendedor: "vendedor",
  loja: "tienda",
  semana: "semana",
  semanas: "semanas",
  recebido_até_hoje: "recibido hasta hoy",
  dois: "dos",
  outro: "otro",
  outra: "otra",
  // positivas / experiencia
  otimo: "óptimo",
  ótimo: "óptimo",
  excelente: "excelente",
  rapido: "rápido",
  rápido: "rápido",
  rapida: "rápida",
  rápida: "rápida",
  perfeito: "perfecto",
  perfeita: "perfecta",
  recomendo: "recomiendo",
  bom: "bueno",
  boa: "buena",
  qualidade: "calidad",
  parabens: "felicitaciones",
  parabéns: "felicitaciones",
  satisfeito: "satisfecho",
  satisfeita: "satisfecha",
  gostei: "me gustó",
  amei: "encantó",
  adorei: "encantó",
  super: "súper",
  antes: "antes",
  prazos: "plazos",
  certo: "correcto",
  certa: "correcta",
  pode: "puede",
  estou: "estoy",
  estamos: "estamos",
  todas: "todas",
  todos: "todos",
  primeira: "primera",
  primeiro: "primero",
  preço: "precio",
  preco: "precio",
  bem: "bien",
  muito: "mucho",
  mais: "más",
  tudo: "todo",
  super_bem: "muy bien",
};

export function palabraEs(pt: string): string {
  return PALABRAS_ES[pt] ?? pt;
}
